### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by firefly-cpp** [lukapecnik/NiaClass#13]
Hi @lukapecnik,

I am attaching several warnings.
 
=============================== warnings summary ===============================
../../../../usr/lib/python3.9/site-packages/NiaPy/algorithms/basic/fss.py:2
../../../../usr/lib/python3.9/site-packages/NiaPy/algorithms/basic/fss.py:2
  /usr/lib/python3.9/site-packages/NiaPy/algorithms/basic/fss.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    from numpy import nan, asarray, zeros, float, full
niaclass/tests/test_run.py: 11 warnings
  /usr/lib64/python3.9/site-packages/numpy/core/_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    return array(a, dtype, copy=False, order=order)
-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 5 passed, 13 warnings in 3.36s ========================

**Comment by firefly-cpp** [comment]
We should report NiaPy warnings to the upstream.

**Comment by firefly-cpp** [comment]
Please check some additional warnings related to docs:

/builddir/build/BUILD/NiaClass-0.1.0/docs/api/niaclass.rst:2: WARNING: Title underline too short.
:mod:`niaclass`
=============
/builddir/build/BUILD/NiaClass-0.1.0/docs/contributing.rst:2: WARNING: Title underline too short.
Contributing to NiaClass
======================

/builddir/build/BUILD/NiaClass-0.1.0/niaclass/__init__.py:docstring of niaclass:1: WARNING: duplicate object description of niaclass, other instance in api/niaclass, use :noindex: for one of them

**Comment by lukapecnik** [comment]
@firefly-cpp please check if these warnings still occur after the update
